Define tables
opensearch-project/dashboards-query-workbench pull request #126
Opened 2023-09-21 06:25 UTC by sumukhswamy

### Description
added changes for flint 
sidebar changes with create and Data-connections tab added
added tables names as indexed
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-09-21 13:56 UTC, derek-ho commented on public/components/Main/main.tsx
> +import { EuiButton, EuiFlexGroup, EuiFlexItem, EuiSpacer, EuiTitle, EuiPageSideBar ,EuiSideNav, EuiPanel, EuiPageTemplate, EuiPage, EuiPageContent, EuiPageContentBody, EuiFlexGrid, EuiSplitPanel, Eui
Can you run `yarn lint`? This should be on different lines I think

2023-09-21 14:04 UTC, derek-ho commented on public/components/app.tsx
> +          <EuiPage paddingSize='none'>
What's the purpose of this?

2023-09-21 14:08 UTC, derek-ho commented on public/components/Main/main.tsx
> +      const schema: object[] = _.get(responseObj, 'schema');
Are you even using the schema for anything?

2023-09-21 14:08 UTC, derek-ho commented on public/components/Main/main.tsx
> +      return data[2]
Why the third element?

2023-09-21 14:09 UTC, derek-ho commented on public/components/Main/main.tsx
> +      let endpoint = '../api/sql_console/sqlquery';
Can we avoid hard coded relative paths? the httpClient should be able to handle cases like this

2023-09-21 14:09 UTC, derek-ho commented on public/components/Main/main.tsx
> +          () => console.log('Successfully updated the states')
Can remove this

2023-09-21 14:10 UTC, derek-ho commented on public/components/Main/main.tsx
> +      // this.onRunSidebar()
Can remove this

2023-09-21 14:11 UTC, derek-ho commented on public/components/Main/main.tsx
> +            </EuiButton>
Without doing so it is hard to read this and understand/paint a picture of what you are showing

2023-09-21 14:12 UTC, derek-ho commented on public/components/SQLPage/TableView.tsx
> +        </>
Can clean this up a bit - i.e. simple if `tablenames.length` return this

2023-09-21 15:59 UTC, ps48 commented on public/components/Main/main.tsx
> +    if (queries.length > 0) {
`const queries` is a constant why are we checking length here?

2023-09-21 17:33 UTC, sumukhswamy commented on public/components/app.tsx
> +          <EuiPage paddingSize='none'>
there was padding in the original flow, which seemed to be removed according to the new figma

2023-09-21 17:37 UTC, sumukhswamy commented on public/components/Main/main.tsx
> +      return data[2]
the way datarows extracts the object is  like this
![image](https://github.com/opensearch-project/dashboards-query-workbench/assets/107440906/51a79336-16dc-4c28-99d0-7aa01bb36ff3)

2023-09-21 17:51 UTC, sumukhswamy commented on public/components/Main/main.tsx
> +      let endpoint = '../api/sql_console/sqlquery';
sure.

2023-09-21 17:52 UTC, sumukhswamy commented on public/components/Main/main.tsx
> +      let endpoint = '../api/sql_console/sqlquery';
Since this will be the same query always, shall I keep in a constant or should i keep it in a variable in the function?

2023-09-22 23:17 UTC, ps48 commented on public/components/SQLPage/TableView.tsx
> +        //     });
remove commented code

2023-09-22 23:18 UTC, ps48 commented on public/components/SQLPage/TableView.tsx
> +        //     });
Can you remove this commented code.

2023-09-22 23:18 UTC, ps48 commented on public/components/SQLPage/TableView.tsx
> +            .post(`../api/sql_console/sqlquery`, {
We should keep the string endpoint in constants

2023-09-22 23:22 UTC, ps48 commented on public/components/Main/main.tsx
> +import { EuiButton, EuiFlexGroup, EuiFlexItem, EuiSpacer, EuiPageSideBar , EuiPanel, EuiPage, EuiPageContent, EuiPageContentBody, EuiComboBox, EuiText, EuiFieldSearch} from '@elastic/eui';
Can you lint the file correctly? These should be in same line.

2023-09-22 23:23 UTC, ps48 commented on public/components/Main/main.tsx
> +      <EuiPage paddingSize='none'>
Minor: You should fragment out these big code pieces in separate files.

2023-09-22 23:24 UTC, ps48 commented on public/components/SQLPage/TableView.tsx
> +    console.log(treeData)
can remove console.log statements.

2023-09-28 17:47 UTC, ps48 commented
@sumukhswamy Can you please sign these commits: 
```
Error: The SoB (DCO) check failed

  7b9038fc00b292fdb009d9e17281c44f2e56e4ec    The sign-off is missing.
  3c337cad7184b7c95531514c1b335f84ab1c22f2    The sign-off is missing.
  c2d241d21964cf729ee6f20053916e469541dc32    The sign-off is missing.
  ```

2023-09-28 20:11 UTC, derek-ho commented on public/components/Main/main.test.tsx
> +    // expect(client.post).not.toHaveBeenCalled();
remove

2023-09-28 20:11 UTC, derek-ho commented on public/components/Main/main.test.tsx
> +    const { getByText } = await render(
is the await necessary here?

2023-09-28 20:13 UTC, derek-ho commented on public/components/Main/main.tsx
> +                const selectedValue = selectedOptions[0] ? selectedOptions[0].value : '';
I thought we were changing this to single select?

2023-09-28 20:13 UTC, derek-ho commented on public/components/Main/main.tsx
> +                const selectedValue = selectedOptions[0] ? selectedOptions[0].value : '';
I think even super select may make more sense here

2023-09-28 20:14 UTC, derek-ho commented on public/components/Main/main.tsx
> +              </EuiPageSideBar>
When possible please extract out to children components to make it more readable. Additionally @ps48 suggested me before - you can do langauge === 'SQL' && <component/> to make it more clear

2023-09-28 20:15 UTC, derek-ho commented on public/components/SQLPage/TableView.tsx
> +            .post(`../api/sql_console/sqlquery`, {
Why are we doing relative paths here? @sumukhswamy please use existing `http` infrastructure if possible. We were running into issues in reporting if there is base path or not

2023-09-28 20:15 UTC, joshuali925 commented on common/constants.ts
> +export const ON_LOAD_QUERY = `SHOW tables LIKE '%';`
missing license header

2023-09-28 20:15 UTC, joshuali925 commented on public/components/Main/main.test.tsx
> +
remove unnecessary change?

2023-09-28 20:15 UTC, joshuali925 commented on public/components/Main/main.tsx
> +import {TableView} from '../SQLPage/TableView'
could you run prettier? otherwise it will introduce unnecessary diffs for future PRs

2023-09-28 20:15 UTC, joshuali925 commented on public/components/Main/main.tsx
> +
revert this?

2023-09-28 20:15 UTC, joshuali925 commented on public/components/Main/main.tsx
> +                this.handleComboOptionChange(selectedValue);
what happens when user selects multiple? should combo box set single selection?

2023-09-28 20:15 UTC, joshuali925 commented on public/components/SQLPage/TableView.tsx
> +                console.error(err);
should user be notified?

2023-09-28 20:17 UTC, derek-ho requested changes
Blocking this PR on this comment: https://github.com/opensearch-project/dashboards-query-workbench/pull/126#discussion_r1340625391

2023-09-28 20:37 UTC, sumukhswamy commented on public/components/Main/main.test.tsx
> +    const { getByText } = await render(
since the component now has the sidebar which has http calls for setting the parameters

2023-09-28 20:37 UTC, sumukhswamy commented on public/components/Main/main.tsx
> +                const selectedValue = selectedOptions[0] ? selectedOptions[0].value : '';
this is just a placeholder will be using Eric code for data selector

2023-09-28 20:45 UTC, sumukhswamy commented on public/components/Main/main.tsx
> +                this.handleComboOptionChange(selectedValue);
this is just a placeholder will be using Eric code for data selector

2023-09-29 17:10 UTC, ps48 approved these changes

2023-09-29 19:42 UTC, derek-ho approved these changes

2023-09-29 19:53 UTC, joshuali925 commented on public/components/SQLPage/TableView.tsx
> +                console.error(err);
if there is an error in the query, will there be a visual indication besides the console message?

2023-09-29 19:54 UTC, joshuali925 commented
could you answer this? https://github.com/opensearch-project/dashboards-query-workbench/pull/126#discussion_r1341744750

2023-09-29 20:09 UTC, sumukhswamy commented on public/components/SQLPage/TableView.tsx
> +                console.error(err);
also for https://github.com/opensearch-project/dashboards-query-workbench/pull/126#discussion_r1340625391 i have made the changes and spoken to Derek about it

2023-09-29 20:33 UTC, joshuali925 commented on public/components/SQLPage/TableView.tsx
> +                console.error(err);
> this is for the side bar, so here will be no visual indication, this is to list the datasources he has available

do we expect this to fail often? my concern is for example user accidentally deleted sql plugin, and workbench can't get the list of datasources but user doesn't know why

2023-09-29 20:34 UTC, sumukhswamy commented on public/components/SQLPage/TableView.tsx
> +                console.error(err);
oh okay , will add cod eto show error if it occurs

2023-09-29 21:56 UTC, sumukhswamy commented on public/components/SQLPage/TableView.tsx
> +                console.error(err);
have added an error message for handling missing data

2023-09-29 22:02 UTC, joshuali925 approved these changes

2023-09-29 22:04 UTC, joshuali925 commented
non blocking: could you set up prettier? the formattings are off with 4 spaces indentation and OSD sets it to 2. we had this issue before, it would introduce unnecessary diffs in other PRs

2023-09-29 23:29 UTC, merged